version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Installing prerequisites"
          command: |
            sudo apt-get update
            sudo apt-get install fuse libfuse2 kmod git libatomic1 libc++1 libx11-6 libxtst6 \
            libasound2 libgtk2.0-0 libxss1 libnspr4 libnss3 appstream-util \
            chromium-codecs-ffmpeg-extra appstream-util
            sudo depmod
            sudo modprobe fuse
            curl -L https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -o linuxdeploy && chmod +x linuxdeploy
            curl https://dl.discordapp.net/apps/linux/0.0.9/discord-0.0.9.tar.gz | tar xzvf -
      - run:
          name: "Building AppImage"
          command: |
            echo "-----BEGIN PGP PRIVATE KEY BLOCK-----" > certificate.asc
            echo "" >> certificate.asc
            echo $SIGN_CERT >> certificate.asc
            echo "-----END PGP PRIVATE KEY BLOCK-----" >> certificate.asc
            gpg --import ./certificate.asc
            mkdir AppDir
            BUILD_HOME="$(pwd)"
            BUILD_APPDIR="$(pwd)/AppDir"
            mkdir -p "${BUILD_APPDIR}/usr/share/icons/hicolor/scalable/apps"
            mkdir -p "${BUILD_APPDIR}/usr/share/metainfo"
            mkdir -p "${BUILD_APPDIR}/usr/bin"
            cp -r Discord "${BUILD_APPDIR}/usr/share/discord"
            chmod +x "${BUILD_APPDIR}/usr/share/discord/Discord"
            cp discord.desktop "${BUILD_APPDIR}"
            cp discord.svg "${BUILD_APPDIR}/usr/share/icons/hicolor/scalable/apps"
            cp com.discordapp.appdata.xml "${BUILD_APPDIR}/usr/share/metainfo"
            cd "${BUILD_APPDIR}/usr/bin"
            ln -s ../share/discord/Discord Discord
            cd "${BUILD_HOME}"
            cat \<< EOF > AppRun
            #!/bin/sh
            cd "\${APPDIR}/usr/share/discord"
            ./Discord
            EOF
            chmod +x ./AppRun
            export SIGN=1
            export ARCH=x86_64
            export UPDATE_INFORMATION="gh-releases-zsync|zilti|discord.AppImage|continuous|Discord-*.AppImage.zsync"
            export LD_LIBRARY_PATH="/usr/lib/chromium-browser"
            export LIBRARY_PATH="/usr/lib/chromium-browser"
            ./linuxdeploy --appdir="${BUILD_APPDIR}" --desktop-file="${BUILD_APPDIR}/discord.desktop" --icon-file="${BUILD_APPDIR}/usr/share/icons/hicolor/scalable/apps/discord.svg" \
            -l/usr/lib/chromium-browser/libffmpeg.so \
            -e"${BUILD_APPDIR}/usr/share/discord/Discord" \
            -oappimage
            export TRAVIS_REPO_SLUG="zilti/discord.AppImage"
            wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
            bash upload.sh *.AppImage*
