version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Installing prerequisites"
          command: |
            sudo apt-get update
            sudo apt-get install fuse libfuse2 kmod git libatomic1 libc++1 libx11-6 libxtst6 \
            libasound2 libgtk2.0-0 libxss1 libnspr4 libnss3
            sudo depmod
            sudo modprobe fuse
            curl -L https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -o linuxdeploy && chmod +x linuxdeploy
            curl https://dl.discordapp.net/apps/linux/0.0.9/discord-0.0.9.tar.gz | tar xzvf -
      - run:
          name: "Building AppImage"
          command: |
            mkdir AppDir
            BUILD_APPDIR="$(pwd)/AppDir"
            mkdir -p "${BUILD_APPDIR}/usr/share/icons/hicolor/scalable/apps"
            mkdir -p "${BUILD_APPDIR}/usr/share/metainfo"
            cp -r Discord "${BUILD_APPDIR}/usr/share/discord"
            chmod +x "${BUILD_APPDIR}/usr/share/discord/Discord"
            cp discord.desktop "${BUILD_APPDIR}"
            cp discord.svg "${BUILD_APPDIR}/usr/share/icons/hicolor/scalable/apps"
            cp com.discordapp.appdata.xml "${BUILD_APPDIR}/usr/share/metainfo"
            export ARCH=x86_64
            export UPDATE_INFORMATION="gh-releases-zsync|zilti|discord.AppImage|continuous|Discord-*.AppImage.zsync"
            ./linuxdeploy --appdir="${BUILD_APPDIR}" --desktop-file="${BUILD_APPDIR}/discord.desktop" --icon-file="${BUILD_APPDIR}/usr/share/icons/hicolor/scalable/apps/discord.svg" \
            -e"${BUILD_APPDIR}/usr/share/discord/Discord" \
            # -l/usr/lib/x86_64-linux-gnu/libnspr4.so \
            # -l/usr/lib/x86_64-linux-gnu/libnss3.so \
            # -l/usr/lib/x86_64-linux-gnu/libnssutil3.so \
            # -l/usr/lib/x86_64-linux-gnu/libplc4.so \
            # -l/usr/lib/x86_64-linux-gnu/libplds4.so \
            # -l/usr/lib/x86_64-linux-gnu/libsmime3.so \
            # -l/usr/lib/x86_64-linux-gnu/libssl3.so \
            # -l/usr/lib/x86_64-linux-gnu/nss/libfreebl3.so \
            # -l/usr/lib/x86_64-linux-gnu/nss/libfreeblpriv3.so \
            # -l/usr/lib/x86_64-linux-gnu/nss/libnssckbi.so \
            # -l/usr/lib/x86_64-linux-gnu/nss/libnssdbm3.so \
            # -l/usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so \
            # -l/usr/lib/x86_64-linux-gnu/libatomic.so.1 \
            # -l/usr/lib/x86_64-linux-gnu/libc++.so.1 \
            # -l/usr/lib/x86_64-linux-gnu/libc++abi.so.1 \
            # -l/usr/lib/x86_64-linux-gnu/libgconf-2.so.4 \
            # -l/usr/lib/x86_64-linux-gnu/libnotify.so.4 \
            # -l/usr/lib/x86_64-linux-gnu/libXss.so.1 \
            # -l/usr/lib/x86_64-linux-gnu/libXtst.so.6 \
            -oappimage
            export TRAVIS_REPO_SLUG="zilti/discord.AppImage"
            wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
            bash upload.sh *.AppImage*
